export const LANGUAGES = [
  {
    code: "en-IN",
    nativeName: "English",
    englishName: "English",
    flag: "🇬🇧",
    states: ["ALL"],
    greetings: { namaste: "Hello! 👋" },
    ui: {
      intro: "I will help you find government schemes you are eligible for.",
      startButton: "Get Started",
      startRecording: "Press to speak",
      stopRecording: "Press to stop",
      searching: "Finding schemes...",
      schemesFound: "schemes found",
    },
  },
  {
    code: "hi-IN",
    nativeName: "हिन्दी",
    englishName: "Hindi",
    flag: "🇮🇳",
    states: ["UP", "MP", "RJ", "HR", "DL", "BR", "UK", "JH", "HP", "CG"],
    greetings: { namaste: "नमस्ते! 🙏" },
    ui: {
      intro: "मैं आपको सरकारी योजनाओं के बारे में बताऊंगा। कुछ सवाल पूछूंगा।",
      startButton: "शुरू करें",
      startRecording: "बोलने के लिए दबाएं",
      stopRecording: "रोकने के लिए दबाएं",
      searching: "योजनाएं खोज रहे हैं...",
      schemesFound: "योजनाएं मिलीं",
    },
  },
  {
    code: "ta-IN",
    nativeName: "தமிழ்",
    englishName: "Tamil",
    flag: "🌺",
    states: ["TN", "PY"],
    greetings: { namaste: "வணக்கம்! 🙏" },
    ui: {
      intro: "அரசு திட்டங்களைப் பற்றி உங்களுக்குத் தெரிவிக்கிறேன். சில கேள்விகள் கேட்கிறேன்.",
      startButton: "தொடங்குங்கள்",
      startRecording: "பேச அழுத்துங்கள்",
      stopRecording: "நிறுத்த அழுத்துங்கள்",
      searching: "திட்டங்களை தேடுகிறோம்...",
      schemesFound: "திட்டங்கள் கிடைத்தன",
    },
  },
  {
    code: "te-IN",
    nativeName: "తెలుగు",
    englishName: "Telugu",
    flag: "🌸",
    states: ["AP", "TS"],
    greetings: { namaste: "నమస్కారం! 🙏" },
    ui: {
      intro: "ప్రభుత్వ పథకాల గురించి మీకు చెప్తాను.",
      startButton: "ప్రారంభించండి",
      startRecording: "మాట్లాడటానికి నొక్కండి",
      stopRecording: "ఆపడానికి నొక్కండి",
      searching: "పథకాలు వెతుకుతున్నాం...",
      schemesFound: "పథకాలు దొరికాయి",
    },
  },
  {
    code: "kn-IN",
    nativeName: "ಕನ್ನಡ",
    englishName: "Kannada",
    flag: "🏵️",
    states: ["KA"],
    greetings: { namaste: "ನಮಸ್ಕಾರ! 🙏" },
    ui: {
      intro: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ತಿಳಿಸುತ್ತೇನೆ.",
      startButton: "ಪ್ರಾರಂಭಿಸಿ",
      startRecording: "ಮಾತನಾಡಲು ಒತ್ತಿ",
      stopRecording: "ನಿಲ್ಲಿಸಲು ಒತ್ತಿ",
      searching: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ...",
      schemesFound: "ಯೋಜನೆಗಳು ಸಿಕ್ಕಿವೆ",
    },
  },
  {
    code: "mr-IN",
    nativeName: "मराठी",
    englishName: "Marathi",
    flag: "🌻",
    states: ["MH"],
    greetings: { namaste: "नमस्कार! 🙏" },
    ui: {
      intro: "मी तुम्हाला सरकारी योजनांबद्दल सांगेन.",
      startButton: "सुरू करा",
      startRecording: "बोलण्यासाठी दाबा",
      stopRecording: "थांबवण्यासाठी दाबा",
      searching: "योजना शोधत आहोत...",
      schemesFound: "योजना सापडल्या",
    },
  },
  {
    code: "bn-IN",
    nativeName: "বাংলা",
    englishName: "Bengali",
    flag: "🌷",
    states: ["WB"],
    greetings: { namaste: "নমস্কার! 🙏" },
    ui: {
      intro: "আমি আপনাকে সরকারি প্রকল্প সম্পর্কে জানাব।",
      startButton: "শুরু করুন",
      startRecording: "কথা বলতে চাপুন",
      stopRecording: "থামাতে চাপুন",
      searching: "প্রকল্প খুঁজছি...",
      schemesFound: "প্রকল্প পাওয়া গেছে",
    },
  },
  {
    code: "gu-IN",
    nativeName: "ગુજરાતી",
    englishName: "Gujarati",
    flag: "🌼",
    states: ["GJ"],
    greetings: { namaste: "નમસ્તે! 🙏" },
    ui: {
      intro: "હું તમને સરકારી યોજનાઓ વિશે જણાવીશ.",
      startButton: "શરૂ કરો",
      startRecording: "બોલવા માટે દબાવો",
      stopRecording: "રોકવા માટે દબાવો",
      searching: "યોજનાઓ શોધી રહ્યા છીએ...",
      schemesFound: "યોજનાઓ મળી",
    },
  },
  {
    code: "ml-IN",
    nativeName: "മലയാളം",
    englishName: "Malayalam",
    flag: "🌴",
    states: ["KL"],
    greetings: { namaste: "നമസ്കാരം! 🙏" },
    ui: {
      intro: "ഞാൻ നിങ്ങൾക്ക് സർക്കാർ പദ്ധതികളെക്കുറിച്ച് പറഞ്ഞുതരാം.",
      startButton: "ആരംഭിക്കുക",
      startRecording: "സംസാരിക്കാൻ അമർത്തുക",
      stopRecording: "നിർത്താൻ അമർത്തുക",
      searching: "പദ്ധതികൾ തിരയുന്നു...",
      schemesFound: "പദ്ധതികൾ കണ്ടെത്തി",
    },
  },
  {
    code: "or-IN",
    nativeName: "ଓଡ଼ିଆ",
    englishName: "Odia",
    flag: "🌺",
    states: ["OD"],
    greetings: { namaste: "ନମସ୍କାର! 🙏" },
    ui: {
      intro: "ମୁଁ ଆପଣଙ୍କୁ ସରକାରୀ ଯୋଜନା ବିଷୟରେ କହିବ।",
      startButton: "ଆରମ୍ଭ କରନ୍ତୁ",
      startRecording: "କହିବାକୁ ଚାପନ୍ତୁ",
      stopRecording: "ରୋକିବାକୁ ଚାପନ୍ତୁ",
      searching: "ଯୋଜନା ଖୋଜୁଛୁ...",
      schemesFound: "ଯୋଜନା ମିଳିଲା",
    },
  },
  {
    code: "pa-IN",
    nativeName: "ਪੰਜਾਬੀ",
    englishName: "Punjabi",
    flag: "🌾",
    states: ["PB"],
    greetings: { namaste: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! 🙏" },
    ui: {
      intro: "ਮੈਂ ਤੁਹਾਨੂੰ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਬਾਰੇ ਦੱਸਾਂਗਾ।",
      startButton: "ਸ਼ੁਰੂ ਕਰੋ",
      startRecording: "ਬੋਲਣ ਲਈ ਦਬਾਓ",
      stopRecording: "ਰੋਕਣ ਲਈ ਦਬਾਓ",
      searching: "ਯੋਜਨਾਵਾਂ ਲੱਭ ਰਹੇ ਹਾਂ...",
      schemesFound: "ਯੋਜਨਾਵਾਂ ਮਿਲੀਆਂ",
    },
  },
] as const;
