export interface Question {
  key: string;
  text: string;
  hint: string;
}

export const QUESTIONS: Record<string, Question[]> = {
  "en-IN": [
    { key: "state", text: "Which state do you live in?", hint: "e.g., Tamil Nadu, Karnataka, Rajasthan..." },
    { key: "age", text: "What is your age?", hint: "e.g., 45 years" },
    { key: "gender", text: "Are you male or female?", hint: "Male / Female" },
    { key: "occupation", text: "What is your occupation?", hint: "Farmer, Student, Merchant, Employee..." },
    { key: "income", text: "What is your annual income?", hint: "e.g., 72,000 Rupees" },
    { key: "land", text: "How much land do you own?", hint: "In acres, or 0 if none" },
    { key: "caste", text: "Which caste category do you belong to?", hint: "SC, ST, OBC, or General" },
    { key: "bpl", text: "Do you have a BPL Ration Card?", hint: "Yes / No" },
  ],
  "hi-IN": [
    { key: "state", text: "आप किस राज्य में रहते हैं?", hint: "उत्तर प्रदेश, तमिलनाडु, महाराष्ट्र..." },
    { key: "age", text: "आपकी उम्र क्या है?", hint: "उदाहरण: 45 साल" },
    { key: "gender", text: "आप महिला हैं या पुरुष?", hint: "महिला / पुरुष" },
    { key: "occupation", text: "आप क्या काम करते हैं?", hint: "किसान, मजदूर, व्यापारी, नौकरी..." },
    { key: "income", text: "आपकी सालाना आमदनी कितनी है?", hint: "उदाहरण: 72,000 रुपये" },
    { key: "land", text: "आपके पास कितनी जमीन है?", hint: "एकड़ में बताएं, नहीं है तो शून्य" },
    { key: "caste", text: "आप किस श्रेणी में आते हैं?", hint: "SC, ST, OBC, या सामान्य" },
    { key: "bpl", text: "क्या आपके पास BPL राशन कार्ड है?", hint: "हाँ / नहीं" },
  ],
  "ta-IN": [
    { key: "state", text: "நீங்கள் எந்த மாநிலத்தில் வசிக்கிறீர்கள்?", hint: "தமிழ்நாடு, கேரளா, கர்நாடகா..." },
    { key: "age", text: "உங்கள் வயது என்ன?", hint: "எடுத்துக்காட்டு: 45 வயது" },
    { key: "gender", text: "நீங்கள் பெண்ணா அல்லது ஆணா?", hint: "பெண் / ஆண்" },
    { key: "occupation", text: "நீங்கள் என்ன வேலை செய்கிறீர்கள்?", hint: "விவசாயி, கூலி தொழிலாளி, வியாபாரி..." },
    { key: "income", text: "உங்கள் ஆண்டு வருமானம் எவ்வளவு?", hint: "எடுத்துக்காட்டு: 72,000 ரூபாய்" },
    { key: "land", text: "உங்களிடம் எவ்வளவு நிலம் உள்ளது?", hint: "ஏக்கரில் சொல்லுங்கள், இல்லையெனில் பூஜ்யம்" },
    { key: "caste", text: "நீங்கள் எந்த வகுப்பைச் சேர்ந்தவர்?", hint: "SC, ST, OBC, அல்லது பொது" },
    { key: "bpl", text: "உங்களிடம் BPL அட்டை இருக்கிறதா?", hint: "ஆமாம் / இல்லை" },
  ],
  "te-IN": [
    { key: "state", text: "మీరు ఏ రాష్ట్రంలో నివసిస్తున్నారు?", hint: "ఆంధ్రప్రదేశ్, తెలంగాణ, కర్ణాటక..." },
    { key: "age", text: "మీ వయస్సు ఎంత?", hint: "ఉదాహరణ: 45 సంవత్సరాలు" },
    { key: "gender", text: "మీరు స్త్రీనా లేదా పురుషుడినా?", hint: "స్త్రీ / పురుషుడు" },
    { key: "occupation", text: "మీరు ఏ పని చేస్తారు?", hint: "రైతు, కూలీ, వ్యాపారి..." },
    { key: "income", text: "మీ వార్షిక ఆదాయం ఎంత?", hint: "ఉదాహరణ: 72,000 రూపాయలు" },
    { key: "land", text: "మీకు ఎంత భూమి ఉంది?", hint: "ఎకరాల్లో చెప్పండి, లేకుంటే సున్న" },
    { key: "caste", text: "మీరు ఏ వర్గానికి చెందిన వారు?", hint: "SC, ST, OBC, లేదా General" },
    { key: "bpl", text: "మీకు BPL రేషన్ కార్డు ఉందా?", hint: "అవును / కాదు" },
  ],
  "kn-IN": [
    { key: "state", text: "ನೀವು ಯಾವ ರಾಜ್ಯದಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?", hint: "ಕರ್ನಾಟಕ, ತಮಿಳುನಾಡು..." },
    { key: "age", text: "ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?", hint: "ಉದಾಹರಣೆ: 45 ವರ್ಷ" },
    { key: "gender", text: "ನೀವು ಮಹಿಳೆಯೇ ಅಥವಾ ಪುರುಷರೇ?", hint: "ಮಹಿಳೆ / ಪುರುಷ" },
    { key: "occupation", text: "ನೀವು ಯಾವ ಕೆಲಸ ಮಾಡುತ್ತೀರಿ?", hint: "ರೈತ, ಕೂಲಿ, ವ್ಯಾಪಾರ..." },
    { key: "income", text: "ನಿಮ್ಮ ವಾರ್ಷಿಕ ಆದಾಯ ಎಷ್ಟು?", hint: "ಉದಾಹರಣೆ: 72,000 ರೂಪಾಯಿ" },
    { key: "land", text: "ನಿಮ್ಮಲ್ಲಿ ಎಷ್ಟು ಜಮೀನು ಇದೆ?", hint: "ಎಕರೆಯಲ್ಲಿ ಹೇಳಿ, ಇಲ್ಲದಿದ್ದರೆ ಸೊನ್ನೆ" },
    { key: "caste", text: "ನೀವು ಯಾವ ವರ್ಗಕ್ಕೆ ಸೇರಿದ್ದೀರಿ?", hint: "SC, ST, OBC, ಅಥವಾ ಸಾಮಾನ್ಯ" },
    { key: "bpl", text: "ನಿಮ್ಮಲ್ಲಿ BPL ರೇಷನ್ ಕಾರ್ಡ್ ಇದೆಯೇ?", hint: "ಹೌದು / ಇಲ್ಲ" },
  ],
  "mr-IN": [
    { key: "state", text: "तुम्ही कोणत्या राज्यात राहता?", hint: "महाराष्ट्र, गुजरात, कर्नाटक..." },
    { key: "age", text: "तुमचे वय किती आहे?", hint: "उदाहरण: 45 वर्षे" },
    { key: "gender", text: "तुम्ही महिला आहात की पुरुष?", hint: "महिला / पुरुष" },
    { key: "occupation", text: "तुम्ही काय काम करता?", hint: "शेतकरी, मजूर, व्यापारी..." },
    { key: "income", text: "तुमचे वार्षिक उत्पन्न किती आहे?", hint: "उदाहरण: 72,000 रुपये" },
    { key: "land", text: "तुमच्याकडे किती जमीन आहे?", hint: "एकरात सांगा, नसेल तर शून्य" },
    { key: "caste", text: "तुम्ही कोणत्या श्रेणीत येता?", hint: "SC, ST, OBC किंवा सामान्य" },
    { key: "bpl", text: "तुमच्याकडे BPL रेशन कार्ड आहे का?", hint: "हो / नाही" },
  ],
  "bn-IN": [
    { key: "state", text: "আপনি কোন রাজ্যে থাকেন?", hint: "পশ্চিমবঙ্গ, ওড়িশা..." },
    { key: "age", text: "আপনার বয়স কত?", hint: "উদাহরণ: ৪৫ বছর" },
    { key: "gender", text: "আপনি মহিলা না পুরুষ?", hint: "মহিলা / পুরুষ" },
    { key: "occupation", text: "আপনি কী কাজ করেন?", hint: "কৃষক, শ্রমিক, ব্যবসায়ী..." },
    { key: "income", text: "আপনার বার্ষিক আয় কত?", hint: "উদাহরণ: ৭২,০০০ টাকা" },
    { key: "land", text: "আপনার কতটুকু জমি আছে?", hint: "একরে বলুন, না থাকলে শূন্য" },
    { key: "caste", text: "আপনি কোন শ্রেণীতে পড়েন?", hint: "SC, ST, OBC, বা সাধারণ" },
    { key: "bpl", text: "আপনার কাছে BPL রেশন কার্ড আছে?", hint: "হ্যাঁ / না" },
  ],
  "gu-IN": [
    { key: "state", text: "તમે કયા રાજ્યમાં રહો છો?", hint: "ગુજરાત, રાજસ્થાન..." },
    { key: "age", text: "તમારી ઉંમર કેટલી છે?", hint: "ઉદાહરણ: 45 વર્ષ" },
    { key: "gender", text: "તમે સ્ત્રી છો કે પુરુષ?", hint: "સ્ત્રી / પુરુષ" },
    { key: "occupation", text: "તમે શું કામ કરો છો?", hint: "ખેડૂત, મજૂર, વ્યાપારી..." },
    { key: "income", text: "તમારી વાર્ષિક આવક કેટલી છે?", hint: "ઉદાહરણ: 72,000 રૂપિયા" },
    { key: "land", text: "તમારી પાસે કેટલી જમીન છે?", hint: "એકરમાં જણાવો, ન હોય તો શૂન્ય" },
    { key: "caste", text: "તમે કઈ શ્રેણીમાં આવો છો?", hint: "SC, ST, OBC, અથવા સામાન્ય" },
    { key: "bpl", text: "શું તમારી પાસે BPL રેશન કાર્ડ છે?", hint: "હા / ના" },
  ],
  "ml-IN": [
    { key: "state", text: "നിങ്ങൾ ഏത് സംസ്ഥാനത്താണ് താമസിക്കുന്നത്?", hint: "കേരളം, തമിഴ്‌നാട്..." },
    { key: "age", text: "നിങ്ങളുടെ പ്രായം എത്രയാണ്?", hint: "ഉദാഹരണം: 45 വയസ്" },
    { key: "gender", text: "നിങ്ങൾ സ്ത്രീയോ പുരുഷനോ?", hint: "സ്ത്രീ / പുരുഷൻ" },
    { key: "occupation", text: "നിങ്ങൾ എന്ത് ജോലി ചെയ്യുന്നു?", hint: "കർഷകൻ, തൊഴിലാളി, വ്യാപാരി..." },
    { key: "income", text: "നിങ്ങളുടെ വാർഷിക വരുമാനം എത്ര?", hint: "ഉദാഹരണം: 72,000 രൂപ" },
    { key: "land", text: "നിങ്ങൾക്ക് എത്ര ഭൂമി ഉണ്ട്?", hint: "ഏക്കറിൽ പറയൂ, ഇല്ലെങ്കിൽ പൂജ്യം" },
    { key: "caste", text: "നിങ്ങൾ ഏത് വിഭാഗത്തിൽ പെടുന്നു?", hint: "SC, ST, OBC, അല്ലെങ്കിൽ General" },
    { key: "bpl", text: "നിങ്ങൾക്ക് BPL റേഷൻ കാർഡ് ഉണ്ടോ?", hint: "ഉണ്ട് / ഇല്ല" },
  ],
  "or-IN": [
    { key: "state", text: "ଆପଣ କେଉଁ ରାଜ୍ୟରେ ରହୁଛନ୍ତି?", hint: "ଓଡ଼ିଶା, ଝାଡ଼ଖଣ୍ଡ..." },
    { key: "age", text: "ଆପଣଙ୍କ ବୟସ କେତେ?", hint: "ଉଦାହରଣ: 45 ବର୍ଷ" },
    { key: "gender", text: "ଆପଣ ମହିଳା ନା ପୁରୁଷ?", hint: "ମହିଳା / ପୁରୁଷ" },
    { key: "occupation", text: "ଆପଣ କ'ଣ କାମ କରନ୍ତି?", hint: "କୃଷକ, ଶ୍ରମିକ, ବ୍ୟବସାୟୀ..." },
    { key: "income", text: "ଆପଣଙ୍କ ବାର୍ଷିକ ଆୟ କେତେ?", hint: "ଉଦାହରଣ: 72,000 ଟଙ୍କା" },
    { key: "land", text: "ଆପଣଙ୍କ ପାଖରେ କେତେ ଜମି ଅଛି?", hint: "ଏକରରେ ବୁଝାନ୍ତୁ, ନ ଥିଲେ ଶୂନ" },
    { key: "caste", text: "ଆପଣ କେଉଁ ଶ୍ରେଣୀରେ ଆସନ୍ତି?", hint: "SC, ST, OBC, ବା ସାଧାରଣ" },
    { key: "bpl", text: "ଆପଣଙ୍କ ପାଖରେ BPL ରାସନ କାର୍ଡ ଅଛି?", hint: "ହଁ / ନା" },
  ],
  "pa-IN": [
    { key: "state", text: "ਤੁਸੀਂ ਕਿਹੜੇ ਰਾਜ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?", hint: "ਪੰਜਾਬ, ਹਰਿਆਣਾ, ਦਿੱਲੀ..." },
    { key: "age", text: "ਤੁਹਾਡੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?", hint: "ਉਦਾਹਰਨ: 45 ਸਾਲ" },
    { key: "gender", text: "ਤੁਸੀਂ ਔਰਤ ਹੋ ਜਾਂ ਮਰਦ?", hint: "ਔਰਤ / ਮਰਦ" },
    { key: "occupation", text: "ਤੁਸੀਂ ਕੀ ਕੰਮ ਕਰਦੇ ਹੋ?", hint: "ਕਿਸਾਨ, ਮਜ਼ਦੂਰ, ਵਪਾਰੀ..." },
    { key: "income", text: "ਤੁਹਾਡੀ ਸਾਲਾਨਾ ਆਮਦਨੀ ਕਿੰਨੀ ਹੈ?", hint: "ਉਦਾਹਰਨ: 72,000 ਰੁਪਏ" },
    { key: "land", text: "ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨੀ ਜ਼ਮੀਨ ਹੈ?", hint: "ਏਕੜ ਵਿੱਚ ਦੱਸੋ, ਨਹੀਂ ਹੈ ਤਾਂ ਜ਼ੀਰੋ" },
    { key: "caste", text: "ਤੁਸੀਂ ਕਿਹੜੀ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਆਉਂਦੇ ਹੋ?", hint: "SC, ST, OBC, ਜਾਂ ਆਮ" },
    { key: "bpl", text: "ਕੀ ਤੁਹਾਡੇ ਕੋਲ BPL ਰਾਸ਼ਨ ਕਾਰਡ ਹੈ?", hint: "ਹਾਂ / ਨਹੀਂ" },
  ],
};
